# Generated by Django 2.1 on 2019-06-25 20:01

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190625_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='37.566535,126.97796919999996', max_length=63),
        ),
    ]
