# Generated by Django 2.1 on 2019-06-25 20:03

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190625_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='37.54965563216749,127.0469284057617', max_length=63),
        ),
    ]
