# Generated by Django 2.1 on 2019-06-27 22:39

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190626_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
