# Generated by Django 2.1 on 2019-08-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitestatus',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='invitestatus',
            name='group',
        ),
        migrations.RemoveField(
            model_name='invitestatus',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='invitestatus',
            name='rejected',
        ),
        migrations.DeleteModel(
            name='InviteStatus',
        ),
    ]
