# Generated by Django 2.1 on 2019-08-26 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extore', '0003_invitestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitedDate', to='extore.Group')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitedDate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
