# Generated by Django 2.1 on 2019-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extore', '0005_auto_20190903_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
